# Generated by Django 4.0.6 on 2022-08-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewery.beer')),
            ],
        ),
        migrations.CreateModel(
            name='Measuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('density', models.FloatField(verbose_name='Плотность')),
                ('data_meas', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('pressure', models.FloatField(blank=True, default=0, verbose_name='Давление')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.tank', verbose_name='Номер')),
            ],
        ),
    ]
